//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCommon.Web.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XCommon.Web.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 		if (Prospect.Application.Culture.Current().Id() === &quot;{0}&quot;)
        ///			return &quot;{1}&quot;;.
        /// </summary>
        internal static string JavaScriptResourceItem {
            get {
                return ResourceManager.GetString("JavaScriptResourceItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prospect.Application.Culture.Add(&quot;{0}&quot;, &quot;{1}&quot;, &quot;{2}&quot;, &quot;{3}&quot;, {4});.
        /// </summary>
        internal static string JavaScriptResourceRegister {
            get {
                return ResourceManager.GetString("JavaScriptResourceRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	{0}: new ko.computed(function () {{
        ///{1}
        ///	}}),.
        /// </summary>
        internal static string JavaScriptResourceValue {
            get {
                return ResourceManager.GetString("JavaScriptResourceValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /***************************************************
        /// * Nunca altere o conteudo desse arquivo 
        /// * diretamente, pois o mesmo foi gerado de 
        /// * forma automatica!
        /// *
        /// * Quando compilar o codigo este será regerado!
        /// ***************************************************/
        ///
        ///.
        /// </summary>
        internal static string NotificacaoArquivo {
            get {
                return ResourceManager.GetString("NotificacaoArquivo", resourceCulture);
            }
        }
    }
}
