//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCommon.ProjectGerator.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AspNet {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AspNet() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XCommon.ProjectGerator.Resources.AspNet", typeof(AspNet).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;MyPetLife&quot;: {
        ///    &quot;UnitTest&quot;: false,
        ///    &quot;Production&quot;: false,
        ///    &quot;ConnectionString&quot;: &quot;Data Source={Server};Initial Catalog={DataBase};Integrated Security=False;User Id={UserName};Password={Password};MultipleActiveResultSets=True;Application Name=App-Dev;Connection Timeout=1200&quot;
        ///  },
        ///  &quot;XCommon&quot;: {
        ///    &quot;Authentication&quot;: {
        ///      &quot;Cookie&quot;: {
        ///        &quot;CookieName&quot;: &quot;Auth&quot;
        ///      },
        ///      &quot;Google&quot;: {
        ///       
        ///      },
        ///      &quot;Facebook&quot;: {
        ///
        ///      },
        ///      &quot;Map&quot;: {
        ///        &quot;UriLogin&quot;: &quot;/login&quot;, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AppSettings {
            get {
                return ResourceManager.GetString("AppSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using Microsoft.AspNetCore.Hosting;
        ///using Microsoft.AspNetCore.Mvc;
        ///using System;
        ///using XCommon.Application;
        ///using XCommon.Extensions.String;
        ///using XCommon.Patterns.Ioc;
        ///using XCommon.Web.Controllers;
        ///
        ///namespace [{namespace}]
        ///{
        ///    public class HomeController : BaseController
        ///    {
        ///        private readonly IHostingEnvironment _hostEnvironment;
        ///
        ///        public HomeController(IHostingEnvironment hostEnvironment)
        ///        {
        ///            _hostEnvironment = hostEnvironment;
        ///        }
        ///
        ///        pu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HomeController {
            get {
                return ResourceManager.GetString("HomeController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Threading.Tasks;
        ///using Microsoft.AspNetCore.Hosting;
        ///
        ///namespace [{namespace}]
        ///{
        ///    public class Program
        ///    {
        ///        public static void Main(string[] args)
        ///        {
        ///            var host = new WebHostBuilder()
        ///                .UseKestrel()
        ///                .UseContentRoot(Directory.GetCurrentDirectory())
        ///                .UseIISIntegration()
        ///                .UseStartup&lt;Startup&gt;()
        ///               [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Program {
            get {
                return ResourceManager.GetString("Program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;dependencies&quot;: {
        ///    &quot;Microsoft.AspNetCore.Authentication.Cookies&quot;: &quot;1.0.0&quot;,
        ///    &quot;Microsoft.AspNetCore.Authentication.Google&quot;: &quot;1.0.0&quot;,
        ///    &quot;Microsoft.AspNetCore.Authentication.Facebook&quot;: &quot;1.0.0&quot;,
        ///    &quot;Microsoft.AspNetCore.Diagnostics&quot;: &quot;1.0.0&quot;,
        ///    &quot;Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore&quot;: &quot;1.0.0&quot;,
        ///    &quot;Microsoft.AspNetCore.Mvc&quot;: &quot;1.0.0&quot;,
        ///    &quot;Microsoft.AspNetCore.Server.IISIntegration&quot;: &quot;1.0.0&quot;,
        ///    &quot;Microsoft.AspNetCore.Server.Kestrel&quot;: &quot;1.0.0&quot;,
        ///    &quot;Microsoft.AspNetCore.Stat [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProjecJson {
            get {
                return ResourceManager.GetString("ProjecJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Project ToolsVersion=&quot;14.0&quot; DefaultTargets=&quot;Build&quot; xmlns=&quot;http://schemas.microsoft.com/developer/msbuild/2003&quot;&gt;
        ///  &lt;PropertyGroup&gt;
        ///    &lt;VisualStudioVersion Condition=&quot;&apos;$(VisualStudioVersion)&apos; == &apos;&apos;&quot;&gt;14.0&lt;/VisualStudioVersion&gt;
        ///    &lt;VSToolsPath Condition=&quot;&apos;$(VSToolsPath)&apos; == &apos;&apos;&quot;&gt;$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)&lt;/VSToolsPath&gt;
        ///  &lt;/PropertyGroup&gt;
        ///  &lt;Import Project=&quot;$(VSToolsPath)\DotNet\Microsoft.DotNet.Props&quot; Condition=&quot;&apos;$(VST [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProjectXproj {
            get {
                return ResourceManager.GetString("ProjectXproj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using Microsoft.AspNetCore.Builder;
        ///using Microsoft.AspNetCore.Hosting;
        ///using Microsoft.AspNetCore.Http;
        ///using Microsoft.Extensions.Configuration;
        ///using Microsoft.Extensions.DependencyInjection;
        ///using Newtonsoft.Json.Serialization;
        ///using XCommon.Application;
        ///using XCommon.Application.Login;
        ///using XCommon.Patterns.Ioc;
        ///using XCommon.Web.Authentication;
        ///using XCommon.Web.Authentication.Ticket;
        ///using XCommon.Web.Extensions;
        ///[{factoryUsing}]
        ///
        ///namespace [{namespace}]
        ///{
        ///    public class Startup
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Startup {
            get {
                return ResourceManager.GetString("Startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;configuration&gt;
        ///
        ///  &lt;!--
        ///    Configure your application settings in appsettings.json. Learn more at http://go.microsoft.com/fwlink/?LinkId=786380
        ///  --&gt;
        ///
        ///  &lt;system.webServer&gt;
        ///    &lt;handlers&gt;
        ///      &lt;add name=&quot;aspNetCore&quot; path=&quot;*&quot; verb=&quot;*&quot; modules=&quot;AspNetCoreModule&quot; resourceType=&quot;Unspecified&quot;/&gt;
        ///    &lt;/handlers&gt;
        ///    &lt;aspNetCore processPath=&quot;%LAUNCHER_PATH%&quot; arguments=&quot;%LAUNCHER_ARGS%&quot; stdoutLogEnabled=&quot;false&quot; stdoutLogFile=&quot;.\logs\stdout&quot; forwardWindowsAuthToken=&quot;f [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WebConfig {
            get {
                return ResourceManager.GetString("WebConfig", resourceCulture);
            }
        }
    }
}
