//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCommon.ProjectGerator.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CSharp {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CSharp() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XCommon.ProjectGerator.Resources.CSharp", typeof(CSharp).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using XCommon.Application.Login;
        ///using XCommon.Patterns.Ioc;
        ///
        ///namespace [{namespace}]
        ///{
        ///    public partial class Register
        ///    {
        ///        public static void RegisterCustom(bool unitTest)
        ///        {
        ///        }
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string FactoryRegister {
            get {
                return ResourceManager.GetString("FactoryRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Reflection;
        ///using System.Resources;
        ///using Microsoft.Extensions.Configuration;
        ///using XCommon.Application.Login;
        ///using XCommon.CodeGerator;
        ///using XCommon.CodeGerator.Configuration;
        ///using XCommon.Application;
        ///using XCommon.Web;
        ///
        ///namespace [{name}].CodeGenerator
        ///{
        ///	public class Program
        ///	{
        ///        private static IApplicationSettings ApplicationSettings { get; set;  }
        ///        
        ///        public static void Main(string[] a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GeneratorProgram {
            get {
                return ResourceManager.GetString("GeneratorProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Project ToolsVersion=&quot;14.0&quot; DefaultTargets=&quot;Build&quot; xmlns=&quot;http://schemas.microsoft.com/developer/msbuild/2003&quot;&gt;
        ///  &lt;PropertyGroup&gt;
        ///    &lt;VisualStudioVersion Condition=&quot;&apos;$(VisualStudioVersion)&apos; == &apos;&apos;&quot;&gt;14.0&lt;/VisualStudioVersion&gt;
        ///    &lt;VSToolsPath Condition=&quot;&apos;$(VSToolsPath)&apos; == &apos;&apos;&quot;&gt;$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)&lt;/VSToolsPath&gt;
        ///  &lt;/PropertyGroup&gt;
        ///
        ///  &lt;Import Project=&quot;$(VSToolsPath)\DotNet\Microsoft.DotNet.Props&quot; Condition=&quot;&apos;$(V [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProjectClassXproj {
            get {
                return ResourceManager.GetString("ProjectClassXproj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;version&quot;: &quot;1.0.0-*&quot;,
        ///  &quot;buildOptions&quot;: {
        ///    &quot;emitEntryPoint&quot;: true
        ///  },
        ///
        ///  &quot;dependencies&quot;: {
        ///    &quot;Microsoft.Extensions.Configuration&quot;: &quot;1.0.0&quot;,
        ///    &quot;Microsoft.Extensions.Configuration.Abstractions&quot;: &quot;1.0.0&quot;,
        ///    &quot;Microsoft.Extensions.Configuration.FileExtensions&quot;: &quot;1.0.0&quot;,
        ///    &quot;Microsoft.Extensions.Configuration.Json&quot;: &quot;1.0.0&quot;,
        ///    &quot;Microsoft.NETCore.App&quot;: {
        ///      &quot;type&quot;: &quot;platform&quot;,
        ///      &quot;version&quot;: &quot;1.0.0&quot;
        ///    },
        ///[{include}]
        ///    &quot;XCommon&quot;: &quot;1.0.32&quot;,
        ///    &quot;XCommon.CodeGerator&quot;: &quot;1.0.3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProjectJsonCodeGenerator {
            get {
                return ResourceManager.GetString("ProjectJsonCodeGenerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;version&quot;: &quot;1.0.0-*&quot;,
        ///
        ///  &quot;dependencies&quot;: {
        ///    &quot;NETStandard.Library&quot;: &quot;1.6.0&quot;,
        ///[{include}]
        ///    &quot;XCommon&quot;: &quot;1.0.28&quot;,
        ///    &quot;XCommon.EF&quot;: &quot;1.0.28&quot;
        ///  },
        ///
        ///  &quot;frameworks&quot;: {
        ///    &quot;netstandard1.6&quot;: {
        ///					&quot;imports&quot;: [
        ///						&quot;dnxcore50&quot;,
        ///						&quot;portable-net452+win81&quot;
        ///					]
        ///    }
        ///  }
        ///}
        ///.
        /// </summary>
        internal static string ProjectJsonConcrecte {
            get {
                return ResourceManager.GetString("ProjectJsonConcrecte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;version&quot;: &quot;1.0.0-*&quot;,
        ///
        ///  &quot;dependencies&quot;: {
        ///    &quot;NETStandard.Library&quot;: &quot;1.6.0&quot;,
        ///[{include}]
        ///    &quot;XCommon&quot;: &quot;1.0.28&quot;,
        ///    &quot;XCommon.EF&quot;: &quot;1.0.28&quot;
        ///  },
        ///
        ///  &quot;frameworks&quot;: {
        ///    &quot;netstandard1.6&quot;: {
        ///      &quot;imports&quot;: &quot;dnxcore50&quot;
        ///    }
        ///  }
        ///}
        ///.
        /// </summary>
        internal static string ProjectJsonContract {
            get {
                return ResourceManager.GetString("ProjectJsonContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;version&quot;: &quot;1.0.0-*&quot;,
        ///
        ///  &quot;dependencies&quot;: {
        ///    &quot;Microsoft.EntityFrameworkCore&quot;: &quot;1.0.0&quot;,
        ///    &quot;Microsoft.EntityFrameworkCore.Sqlite&quot;: &quot;1.0.0&quot;,
        ///    &quot;Microsoft.EntityFrameworkCore.SqlServer&quot;: &quot;1.0.0&quot;,
        ///    &quot;NETStandard.Library&quot;: &quot;1.6.0&quot;,
        ///[{include}]
        ///    &quot;XCommon&quot;: &quot;1.0.28&quot;
        ///  },
        ///
        ///  &quot;frameworks&quot;: {
        ///    &quot;netstandard1.6&quot;: {
        ///					&quot;imports&quot;: [
        ///						&quot;dnxcore50&quot;,
        ///						&quot;portable-net452+win81&quot;
        ///					]
        ///    }
        ///  }
        ///}
        ///.
        /// </summary>
        internal static string ProjectJsonData {
            get {
                return ResourceManager.GetString("ProjectJsonData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;version&quot;: &quot;1.0.0-*&quot;,
        ///
        ///  &quot;dependencies&quot;: {
        ///    &quot;NETStandard.Library&quot;: &quot;1.6.0&quot;,
        ///    &quot;XCommon&quot;: &quot;1.0.28&quot;
        ///  },
        ///
        ///  &quot;frameworks&quot;: {
        ///    &quot;netstandard1.6&quot;: {
        ///      &quot;imports&quot;: &quot;dnxcore50&quot;
        ///    }
        ///  }
        ///}
        ///.
        /// </summary>
        internal static string ProjectJsonEntity {
            get {
                return ResourceManager.GetString("ProjectJsonEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;version&quot;: &quot;1.0.0-*&quot;,
        ///
        ///  &quot;dependencies&quot;: {
        ///    &quot;NETStandard.Library&quot;: &quot;1.6.0&quot;,
        ///[{include}]
        ///    &quot;XCommon&quot;: &quot;1.0.28&quot;
        ///  },
        ///
        ///  &quot;frameworks&quot;: {
        ///    &quot;netstandard1.6&quot;: {
        ///					&quot;imports&quot;: [
        ///						&quot;dnxcore50&quot;,
        ///						&quot;portable-net452+win81&quot;
        ///					]
        ///    }
        ///  }
        ///}
        ///.
        /// </summary>
        internal static string ProjectJsonFactory {
            get {
                return ResourceManager.GetString("ProjectJsonFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;version&quot;: &quot;1.0.0-*&quot;,
        ///
        ///  &quot;dependencies&quot;: {
        ///    &quot;NETStandard.Library&quot;: &quot;1.6.0&quot;
        ///  },
        ///
        ///  &quot;frameworks&quot;: {
        ///    &quot;netstandard1.6&quot;: {
        ///      &quot;imports&quot;: &quot;dnxcore50&quot;
        ///    }
        ///  }
        ///}
        ///.
        /// </summary>
        internal static string ProjectJsonResource {
            get {
                return ResourceManager.GetString("ProjectJsonResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Microsoft Visual Studio Solution File, Format Version 12.00
        ///# Visual Studio 14
        ///VisualStudioVersion = 14.0.25420.1
        ///MinimumVisualStudioVersion = 10.0.40219.1
        ///[{projects}]
        ///Global
        ///	GlobalSection(SolutionConfigurationPlatforms) = preSolution
        ///		Debug|Any CPU = Debug|Any CPU
        ///		Release|Any CPU = Release|Any CPU
        ///	EndGlobalSection
        ///	GlobalSection(ProjectConfigurationPlatforms) = postSolution
        ///[{link}]
        ///	EndGlobalSection
        ///	GlobalSection(SolutionProperties) = preSolution
        ///		HideSolutionNode = FALSE
        ///	EndGlob [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Solution {
            get {
                return ResourceManager.GetString("Solution", resourceCulture);
            }
        }
    }
}
