//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCommon.ProjectGerator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XCommon.ProjectGerator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using XCommon.Application.Login;
        ///using XCommon.Patterns.Ioc;
        ///
        ///namespace [{namespace}]
        ///{
        ///    public partial class Register
        ///    {
        ///        public static void RegisterCustom(bool unitTest)
        ///        {
        ///        }
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string FactoryRegister {
            get {
                return ResourceManager.GetString("FactoryRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /// &lt;binding ProjectOpened=&apos;dev:watch&apos; /&gt;
        ///var gulp = require(&apos;gulp&apos;),
        ///	gutil = require(&apos;gulp-util&apos;),
        ///	webpack = require(&apos;webpack&apos;),
        ///	htmlmin = require(&apos;gulp-htmlmin&apos;),
        ///	shell = require(&apos;gulp-shell&apos;),
        ///	livereload = require(&quot;gulp-livereload&quot;),
        ///	rimraf = require(&quot;gulp-rimraf&quot;),
        ///	webpackStream = require(&quot;webpack-stream&quot;),
        ///	merge = require(&apos;webpack-merge&apos;);
        ///
        ///var helper = {
        ///	tasks: {
        ///		clear: &quot;clear&quot;,
        ///		watch: &quot;dev:watch&quot;,
        ///		html: {
        ///			page: &quot;dev:html:page&quot;
        ///		},
        ///		dnx: {
        ///		    ts: &quot;dnx:typescri [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GulpFile {
            get {
                return ResourceManager.GetString("GulpFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /// &lt;binding ProjectOpened=&apos;dev:watch&apos; /&gt;
        ///var gulp = require(&apos;gulp&apos;),
        ///	gutil = require(&apos;gulp-util&apos;),
        ///	webpack = require(&apos;webpack&apos;),
        ///	htmlmin = require(&apos;gulp-htmlmin&apos;),
        ///	shell = require(&apos;gulp-shell&apos;),
        ///	livereload = require(&quot;gulp-livereload&quot;),
        ///	rimraf = require(&quot;gulp-rimraf&quot;),
        ///	webpackStream = require(&quot;webpack-stream&quot;),
        ///	merge = require(&apos;webpack-merge&apos;);
        ///
        ///var helper = {
        ///	tasks: {
        ///		clear: &quot;clear&quot;,
        ///		watch: &quot;dev:watch&quot;,
        ///		html: {
        ///			page: &quot;dev:html:page&quot;
        ///		},
        ///		default: {
        ///			dev: &quot;default:de [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GulpFileSimple {
            get {
                return ResourceManager.GetString("GulpFileSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;author&quot;: &quot;&quot;,
        ///  &quot;description&quot;: &quot;&quot;,
        ///  &quot;dependencies&quot;: {
        ///    &quot;@angular/common&quot;: &quot;2.0.0-rc.3&quot;,
        ///    &quot;@angular/compiler&quot;: &quot;2.0.0-rc.3&quot;,
        ///    &quot;@angular/core&quot;: &quot;2.0.0-rc.3&quot;,
        ///    &quot;@angular/http&quot;: &quot;2.0.0-rc.3&quot;,
        ///    &quot;@angular/platform-browser&quot;: &quot;2.0.0-rc.3&quot;,
        ///    &quot;@angular/platform-browser-dynamic&quot;: &quot;2.0.0-rc.3&quot;,
        ///    &quot;@angular/router&quot;: &quot;3.0.0-alpha.7&quot;,
        ///    &quot;core-js&quot;: &quot;^2.4.0&quot;,
        ///    &quot;reflect-metadata&quot;: &quot;^0.1.3&quot;,
        ///    &quot;rxjs&quot;: &quot;5.0.0-beta.6&quot;,
        ///    &quot;zone.js&quot;: &quot;0.6.12&quot;,
        ///    &quot;@angular2-material/button&quot;: &quot;^2.0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PackageJson {
            get {
                return ResourceManager.GetString("PackageJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;version&quot;: &quot;1.0.0-*&quot;,
        ///  &quot;buildOptions&quot;: {
        ///    &quot;emitEntryPoint&quot;: true
        ///  },
        ///
        ///  &quot;dependencies&quot;: {
        ///    &quot;Microsoft.NETCore.App&quot;: {
        ///      &quot;type&quot;: &quot;platform&quot;,
        ///      &quot;version&quot;: &quot;1.0.0&quot;
        ///    },
        ///[{include}]
        ///    &quot;XCommon&quot;: &quot;1.0.28&quot;,
        ///    &quot;XCommon.CodeGerator&quot;: &quot;1.0.28&quot;
        ///  },
        ///
        ///  &quot;frameworks&quot;: {
        ///    &quot;netcoreapp1.0&quot;: {
        ///      &quot;imports&quot;: &quot;dnxcore50&quot;
        ///    }
        ///  }
        ///}
        ///.
        /// </summary>
        internal static string ProjectBusinessCodeGeneratorJson {
            get {
                return ResourceManager.GetString("ProjectBusinessCodeGeneratorJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;version&quot;: &quot;1.0.0-*&quot;,
        ///
        ///  &quot;dependencies&quot;: {
        ///    &quot;NETStandard.Library&quot;: &quot;1.6.0&quot;,
        ///[{include}]
        ///    &quot;XCommon&quot;: &quot;1.0.28&quot;,
        ///    &quot;XCommon.EF&quot;: &quot;1.0.28&quot;
        ///  },
        ///
        ///  &quot;frameworks&quot;: {
        ///    &quot;netstandard1.6&quot;: {
        ///					&quot;imports&quot;: [
        ///						&quot;dnxcore50&quot;,
        ///						&quot;portable-net452+win81&quot;
        ///					]
        ///    }
        ///  }
        ///}
        ///.
        /// </summary>
        internal static string ProjectBusinessConcrectJson {
            get {
                return ResourceManager.GetString("ProjectBusinessConcrectJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;version&quot;: &quot;1.0.0-*&quot;,
        ///
        ///  &quot;dependencies&quot;: {
        ///    &quot;NETStandard.Library&quot;: &quot;1.6.0&quot;,
        ///[{include}]
        ///    &quot;XCommon&quot;: &quot;1.0.28&quot;,
        ///    &quot;XCommon.EF&quot;: &quot;1.0.28&quot;
        ///  },
        ///
        ///  &quot;frameworks&quot;: {
        ///    &quot;netstandard1.6&quot;: {
        ///      &quot;imports&quot;: &quot;dnxcore50&quot;
        ///    }
        ///  }
        ///}
        ///.
        /// </summary>
        internal static string ProjectBusinessContractJson {
            get {
                return ResourceManager.GetString("ProjectBusinessContractJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;version&quot;: &quot;1.0.0-*&quot;,
        ///
        ///  &quot;dependencies&quot;: {
        ///    &quot;Microsoft.EntityFrameworkCore&quot;: &quot;1.0.0&quot;,
        ///    &quot;Microsoft.EntityFrameworkCore.Sqlite&quot;: &quot;1.0.0&quot;,
        ///    &quot;Microsoft.EntityFrameworkCore.SqlServer&quot;: &quot;1.0.0&quot;,
        ///    &quot;NETStandard.Library&quot;: &quot;1.6.0&quot;,
        ///[{include}]
        ///    &quot;XCommon&quot;: &quot;1.0.28&quot;
        ///  },
        ///
        ///  &quot;frameworks&quot;: {
        ///    &quot;netstandard1.6&quot;: {
        ///					&quot;imports&quot;: [
        ///						&quot;dnxcore50&quot;,
        ///						&quot;portable-net452+win81&quot;
        ///					]
        ///    }
        ///  }
        ///}
        ///.
        /// </summary>
        internal static string ProjectBusinessDataJson {
            get {
                return ResourceManager.GetString("ProjectBusinessDataJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;version&quot;: &quot;1.0.0-*&quot;,
        ///
        ///  &quot;dependencies&quot;: {
        ///    &quot;NETStandard.Library&quot;: &quot;1.6.0&quot;,
        ///    &quot;XCommon&quot;: &quot;1.0.28&quot;
        ///  },
        ///
        ///  &quot;frameworks&quot;: {
        ///    &quot;netstandard1.6&quot;: {
        ///      &quot;imports&quot;: &quot;dnxcore50&quot;
        ///    }
        ///  }
        ///}
        ///.
        /// </summary>
        internal static string ProjectBusinessEntityJson {
            get {
                return ResourceManager.GetString("ProjectBusinessEntityJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;version&quot;: &quot;1.0.0-*&quot;,
        ///
        ///  &quot;dependencies&quot;: {
        ///    &quot;NETStandard.Library&quot;: &quot;1.6.0&quot;,
        ///[{include}]
        ///    &quot;XCommon&quot;: &quot;1.0.28&quot;
        ///  },
        ///
        ///  &quot;frameworks&quot;: {
        ///    &quot;netstandard1.6&quot;: {
        ///					&quot;imports&quot;: [
        ///						&quot;dnxcore50&quot;,
        ///						&quot;portable-net452+win81&quot;
        ///					]
        ///    }
        ///  }
        ///}
        ///.
        /// </summary>
        internal static string ProjectBusinessFactoryJson {
            get {
                return ResourceManager.GetString("ProjectBusinessFactoryJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;version&quot;: &quot;1.0.0-*&quot;,
        ///
        ///  &quot;dependencies&quot;: {
        ///    &quot;NETStandard.Library&quot;: &quot;1.6.0&quot;
        ///  },
        ///
        ///  &quot;frameworks&quot;: {
        ///    &quot;netstandard1.6&quot;: {
        ///      &quot;imports&quot;: &quot;dnxcore50&quot;
        ///    }
        ///  }
        ///}
        ///.
        /// </summary>
        internal static string ProjectBusinessResourceJson {
            get {
                return ResourceManager.GetString("ProjectBusinessResourceJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Project ToolsVersion=&quot;14.0&quot; DefaultTargets=&quot;Build&quot; xmlns=&quot;http://schemas.microsoft.com/developer/msbuild/2003&quot;&gt;
        ///  &lt;PropertyGroup&gt;
        ///    &lt;VisualStudioVersion Condition=&quot;&apos;$(VisualStudioVersion)&apos; == &apos;&apos;&quot;&gt;14.0&lt;/VisualStudioVersion&gt;
        ///    &lt;VSToolsPath Condition=&quot;&apos;$(VSToolsPath)&apos; == &apos;&apos;&quot;&gt;$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)&lt;/VSToolsPath&gt;
        ///  &lt;/PropertyGroup&gt;
        ///
        ///  &lt;Import Project=&quot;$(VSToolsPath)\DotNet\Microsoft.DotNet.Props&quot; Condition=&quot;&apos;$(V [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProjectClassXproj {
            get {
                return ResourceManager.GetString("ProjectClassXproj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;dependencies&quot;: {
        ///    &quot;Microsoft.AspNetCore.Authentication.Cookies&quot;: &quot;1.0.0&quot;,
        ///    &quot;Microsoft.AspNetCore.Authentication.Google&quot;: &quot;1.0.0&quot;,
        ///    &quot;Microsoft.AspNetCore.Authentication.Facebook&quot;: &quot;1.0.0&quot;,
        ///    &quot;Microsoft.AspNetCore.Diagnostics&quot;: &quot;1.0.0&quot;,
        ///    &quot;Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore&quot;: &quot;1.0.0&quot;,
        ///    &quot;Microsoft.AspNetCore.Mvc&quot;: &quot;1.0.0&quot;,
        ///    &quot;Microsoft.AspNetCore.Server.IISIntegration&quot;: &quot;1.0.0&quot;,
        ///    &quot;Microsoft.AspNetCore.Server.Kestrel&quot;: &quot;1.0.0&quot;,
        ///    &quot;Microsoft.AspNetCore.Stat [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProjectViewWebJson {
            get {
                return ResourceManager.GetString("ProjectViewWebJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Project ToolsVersion=&quot;14.0&quot; DefaultTargets=&quot;Build&quot; xmlns=&quot;http://schemas.microsoft.com/developer/msbuild/2003&quot;&gt;
        ///  &lt;PropertyGroup&gt;
        ///    &lt;VisualStudioVersion Condition=&quot;&apos;$(VisualStudioVersion)&apos; == &apos;&apos;&quot;&gt;14.0&lt;/VisualStudioVersion&gt;
        ///    &lt;VSToolsPath Condition=&quot;&apos;$(VSToolsPath)&apos; == &apos;&apos;&quot;&gt;$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)&lt;/VSToolsPath&gt;
        ///  &lt;/PropertyGroup&gt;
        ///  &lt;Import Project=&quot;$(VSToolsPath)\DotNet\Microsoft.DotNet.Props&quot; Condition=&quot;&apos;$(VST [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProjectWebXproj {
            get {
                return ResourceManager.GetString("ProjectWebXproj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Microsoft Visual Studio Solution File, Format Version 12.00
        ///# Visual Studio 14
        ///VisualStudioVersion = 14.0.25420.1
        ///MinimumVisualStudioVersion = 10.0.40219.1
        ///[{projects}]
        ///Global
        ///	GlobalSection(SolutionConfigurationPlatforms) = preSolution
        ///		Debug|Any CPU = Debug|Any CPU
        ///		Release|Any CPU = Release|Any CPU
        ///	EndGlobalSection
        ///	GlobalSection(ProjectConfigurationPlatforms) = postSolution
        ///[{link}]
        ///	EndGlobalSection
        ///	GlobalSection(SolutionProperties) = preSolution
        ///		HideSolutionNode = FALSE
        ///	EndGlob [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Solution {
            get {
                return ResourceManager.GetString("Solution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;compilerOptions&quot;: {
        ///		&quot;target&quot;: &quot;es5&quot;,
        ///		&quot;module&quot;: &quot;commonjs&quot;,
        ///		&quot;moduleResolution&quot;: &quot;node&quot;,
        ///		&quot;sourceMap&quot;: true,
        ///		&quot;emitDecoratorMetadata&quot;: true,
        ///		&quot;experimentalDecorators&quot;: true,
        ///		&quot;removeComments&quot;: false,
        ///		&quot;noImplicitAny&quot;: true,
        ///		&quot;suppressImplicitAnyIndexErrors&quot;: true
        ///	}
        ///}
        ///.
        /// </summary>
        internal static string TsConfigJson {
            get {
                return ResourceManager.GetString("TsConfigJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;globalDependencies&quot;: {
        ///    &quot;core-js&quot;: &quot;registry:dt/core-js#0.0.0+20160317120654&quot;,
        ///    &quot;jasmine&quot;: &quot;registry:dt/jasmine#2.2.0+20160505161446&quot;,
        ///    &quot;node&quot;: &quot;registry:dt/node#4.0.0+20160509154515&quot;,
        ///    &quot;hammerjs&quot;: &quot;registry:dt/hammerjs#2.0.4+20160417130828&quot;
        ///  }
        ///}
        ///.
        /// </summary>
        internal static string TypingsJson {
            get {
                return ResourceManager.GetString("TypingsJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot;&gt;
        ///    &lt;title&gt;My App&lt;/title&gt;
        ///    &lt;base href=&quot;/&quot;&gt;
        ///    &lt;link rel=&quot;icon&quot; type=&quot;image/x-icon&quot; href=&quot;favicon.ico&quot;&gt;
        ///    &lt;link href=&quot;/assets/bundle.css&quot; rel=&quot;stylesheet&quot; /&gt;
        ///    &lt;link href=&quot;https://fonts.googleapis.com/icon?family=Material+Icons&quot; rel=&quot;stylesheet&quot;&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;app-root&gt;Whait&lt;/app-root&gt;
        ///    &lt;script type=&quot;text/javascript&quot;&gt;{0}&lt;/script&gt;
        ///    &lt;script type=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WebAngularIndex {
            get {
                return ResourceManager.GetString("WebAngularIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to import { bootstrap } from &quot;@angular/platform-browser-dynamic&quot;;
        ///import { AppComponent } from &quot;./Components/&quot;;
        ///
        ///bootstrap(AppComponent)
        ///    .catch((reason: any) =&gt; console.error(reason));
        ///
        ///.
        /// </summary>
        internal static string WebAngularMain {
            get {
                return ResourceManager.GetString("WebAngularMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to import &apos;core-js/es6&apos;;
        ///import &apos;reflect-metadata&apos;;
        ///require(&apos;zone.js/dist/zone&apos;);.
        /// </summary>
        internal static string WebAngularPolyfills {
            get {
                return ResourceManager.GetString("WebAngularPolyfills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to import &quot;@angular/platform-browser&quot;;
        ///import &quot;@angular/platform-browser-dynamic&quot;;
        ///import &quot;@angular/core&quot;;
        ///import &quot;@angular/common&quot;;
        ///import &quot;@angular/http&quot;;
        ///import &quot;@angular/router&quot;;
        ///import &quot;@angular/forms&quot;;
        ///
        ///import &quot;rxjs&quot;;
        ///
        ///import &quot;@angular2-material/core&quot;;
        ///import &quot;@angular2-material/button&quot;;
        ///import &quot;@angular2-material/card&quot;;
        ///import &quot;@angular2-material/checkbox&quot;;
        ///import &quot;@angular2-material/sidenav&quot;;
        ///import &quot;@angular2-material/input&quot;;
        ///import &quot;@angular2-material/list&quot;;
        ///import &quot;@angular2-materia [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WebAngularVendor {
            get {
                return ResourceManager.GetString("WebAngularVendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1&gt;
        ///  {{ Title }}
        ///&lt;/h1&gt;
        ///.
        /// </summary>
        internal static string WebAppComponentHTML {
            get {
                return ResourceManager.GetString("WebAppComponentHTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to export * from &apos;./app.component&apos;;.
        /// </summary>
        internal static string WebAppComponentIndex {
            get {
                return ResourceManager.GetString("WebAppComponentIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string WebAppComponentStyle {
            get {
                return ResourceManager.GetString("WebAppComponentStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to import { Component } from &quot;@angular/core&quot;;
        ///
        ///@Component({
        ///  selector: &quot;app-root&quot;,
        ///  templateUrl: &quot;/html/components/home/app.component.html&quot;,
        ///  styleUrls: [require(&quot;./app.component.scss&quot;)]
        ///})
        ///export class AppComponent {
        ///  Title = &quot;App works!&quot;;
        ///}
        ///.
        /// </summary>
        internal static string WebAppComponentType {
            get {
                return ResourceManager.GetString("WebAppComponentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;MyPetLife&quot;: {
        ///    &quot;UnitTest&quot;: false,
        ///    &quot;Production&quot;: false,
        ///    &quot;ConnectionString&quot;: &quot;Data Source={Server};Initial Catalog={DataBase};Integrated Security=False;User Id={UserName};Password={Password};MultipleActiveResultSets=True;Application Name=App-Dev;Connection Timeout=1200&quot;
        ///  },
        ///  &quot;XCommon&quot;: {
        ///    &quot;Authentication&quot;: {
        ///      &quot;Cookie&quot;: {
        ///        &quot;CookieName&quot;: &quot;Auth&quot;
        ///      },
        ///      &quot;Google&quot;: {
        ///       
        ///      },
        ///      &quot;Facebook&quot;: {
        ///
        ///      },
        ///      &quot;Map&quot;: {
        ///        &quot;UriLogin&quot;: &quot;/login&quot;, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WebAppSettings {
            get {
                return ResourceManager.GetString("WebAppSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using Microsoft.AspNetCore.Hosting;
        ///using Microsoft.AspNetCore.Mvc;
        ///using System;
        ///using XCommon.Application;
        ///using XCommon.Extensions.String;
        ///using XCommon.Patterns.Ioc;
        ///using XCommon.Web.Controllers;
        ///
        ///namespace [{namespace}]
        ///{
        ///    public class HomeController : BaseController
        ///    {
        ///        private readonly IHostingEnvironment _hostEnvironment;
        ///
        ///        public HomeController(IHostingEnvironment hostEnvironment)
        ///        {
        ///            _hostEnvironment = hostEnvironment;
        ///        }
        ///
        ///        pu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WebAppStartHomeController {
            get {
                return ResourceManager.GetString("WebAppStartHomeController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Threading.Tasks;
        ///using Microsoft.AspNetCore.Hosting;
        ///
        ///namespace [{namespace}]
        ///{
        ///    public class Program
        ///    {
        ///        public static void Main(string[] args)
        ///        {
        ///            var host = new WebHostBuilder()
        ///                .UseKestrel()
        ///                .UseContentRoot(Directory.GetCurrentDirectory())
        ///                .UseIISIntegration()
        ///                .UseStartup&lt;Startup&gt;()
        ///               [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WebAppStartProgram {
            get {
                return ResourceManager.GetString("WebAppStartProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using Microsoft.AspNetCore.Builder;
        ///using Microsoft.AspNetCore.Hosting;
        ///using Microsoft.AspNetCore.Http;
        ///using Microsoft.Extensions.Configuration;
        ///using Microsoft.Extensions.DependencyInjection;
        ///using Newtonsoft.Json.Serialization;
        ///using XCommon.Application;
        ///using XCommon.Application.Login;
        ///using XCommon.Patterns.Ioc;
        ///using XCommon.Web.Authentication;
        ///using XCommon.Web.Authentication.Ticket;
        ///using XCommon.Web.Extensions;
        ///[{factoryUsing}]
        ///
        ///namespace [{namespace}]
        ///{
        ///    public class Startup
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WebAppStartStartup {
            get {
                return ResourceManager.GetString("WebAppStartStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /// &lt;reference path=&quot;App.Variables.scss&quot; /&gt;
        ///@import &quot;App.Variables.scss&quot;;
        ///
        ///body {
        ///	margin: 0;
        ///	padding: 0;
        ///    font-family: Roboto, &quot;Helvetica Neue&quot;, sans-serif;
        ///}
        ///
        ///* {
        ///	-webkit-font-smoothing: antialiased;
        ///	-moz-osx-font-smoothing: grayscale;
        ///}
        ///
        ///.facebook {
        ///	background-color: $Social-Facebook-Color !important;
        ///}
        ///
        ///.google {
        ///	background-color: $Social-Google-Color !important;
        ///}
        ///.
        /// </summary>
        internal static string WebAppThemeScss {
            get {
                return ResourceManager.GetString("WebAppThemeScss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $font-stack: Helvetica, sans-serif;
        ///$primary-color: #333;
        ///$Social-Google-Color: #dd4b39;
        ///$Social-Facebook-Color: #3b5998;
        ///.
        /// </summary>
        internal static string WebAppVariablesScss {
            get {
                return ResourceManager.GetString("WebAppVariablesScss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;configuration&gt;
        ///
        ///  &lt;!--
        ///    Configure your application settings in appsettings.json. Learn more at http://go.microsoft.com/fwlink/?LinkId=786380
        ///  --&gt;
        ///
        ///  &lt;system.webServer&gt;
        ///    &lt;handlers&gt;
        ///      &lt;add name=&quot;aspNetCore&quot; path=&quot;*&quot; verb=&quot;*&quot; modules=&quot;AspNetCoreModule&quot; resourceType=&quot;Unspecified&quot;/&gt;
        ///    &lt;/handlers&gt;
        ///    &lt;aspNetCore processPath=&quot;%LAUNCHER_PATH%&quot; arguments=&quot;%LAUNCHER_ARGS%&quot; stdoutLogEnabled=&quot;false&quot; stdoutLogFile=&quot;.\logs\stdout&quot; forwardWindowsAuthToken=&quot;f [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WebConfig {
            get {
                return ResourceManager.GetString("WebConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var path = require(&apos;path&apos;),
        ///	ExtractTextPlugin = require(&quot;extract-text-webpack-plugin&quot;),
        ///	webpack = require(&apos;webpack&apos;);
        ///
        ///module.exports = {
        ///	entry: [
        ///		&quot;./app/polyfills.ts&quot;,
        ///		&quot;./app/vendor.ts&quot;,
        ///		&quot;./app/main.ts&quot;,
        ///        &quot;./app/styles/app.theme.scss&quot;
        ///	],
        ///	output: {
        ///		path: path.join(__dirname, &quot;wwwroot&quot;, &quot;asserts&quot;),
        ///		filename: &quot;bundle.js&quot;
        ///	},
        ///	plugins: [
        ///		new ExtractTextPlugin(&quot;bundle.css&quot;)
        ///	],
        ///
        ///	resolve: {
        ///		extensions: [&quot;&quot;, &quot;.js&quot;, &quot;.ts&quot;, &quot;.scss&quot;, &quot;.css&quot;]
        ///	},
        ///
        ///	module: {
        ///		loader [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WebpackConfig {
            get {
                return ResourceManager.GetString("WebpackConfig", resourceCulture);
            }
        }
    }
}
