//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCommon.ProjectGerator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XCommon.ProjectGerator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;MyPetLife&quot;: {
        ///    &quot;UnitTest&quot;: false,
        ///    &quot;Production&quot;: false,
        ///    &quot;ConnectionString&quot;: &quot;Data Source={Server};Initial Catalog={DataBase};Integrated Security=False;User Id={UserName};Password={Password};MultipleActiveResultSets=True;Application Name=App-Dev;Connection Timeout=1200&quot;
        ///  },
        ///  &quot;XCommon&quot;: {
        ///    &quot;Authentication&quot;: {
        ///      &quot;Cookie&quot;: {
        ///        &quot;CookieName&quot;: &quot;Auth&quot;
        ///      },
        ///      &quot;Google&quot;: {
        ///       
        ///      },
        ///      &quot;Facebook&quot;: {
        ///
        ///      },
        ///      &quot;Map&quot;: {
        ///        &quot;UriLogin&quot;: &quot;/login&quot;, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string appsettings {
            get {
                return ResourceManager.GetString("appsettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using Microsoft.AspNetCore.Hosting;
        ///using Microsoft.AspNetCore.Mvc;
        ///using System;
        ///using XCommon.Application;
        ///using XCommon.Extensions.String;
        ///using XCommon.Patterns.Ioc;
        ///using XCommon.Web.Controllers;
        ///
        ///namespace [{namespace}]
        ///{
        ///    public class HomeController : BaseController
        ///    {
        ///        private readonly IHostingEnvironment _hostEnvironment;
        ///
        ///        private IApplicationSettings ApplicationSettings =&gt; Kernel.Resolve&lt;IApplicationSettings&gt;();
        ///
        ///        public HomeController(IHostingEnvironmen [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AppStartHomeController {
            get {
                return ResourceManager.GetString("AppStartHomeController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Threading.Tasks;
        ///using Microsoft.AspNetCore.Hosting;
        ///
        ///namespace [{namespace}]
        ///{
        ///    public class Program
        ///    {
        ///        public static void Main(string[] args)
        ///        {
        ///            var host = new WebHostBuilder()
        ///                .UseKestrel()
        ///                .UseContentRoot(Directory.GetCurrentDirectory())
        ///                .UseIISIntegration()
        ///                .UseStartup&lt;Startup&gt;()
        ///               [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AppStartProgram {
            get {
                return ResourceManager.GetString("AppStartProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using Microsoft.AspNetCore.Builder;
        ///using Microsoft.AspNetCore.Hosting;
        ///using Microsoft.AspNetCore.Http;
        ///using Microsoft.Extensions.Configuration;
        ///using Microsoft.Extensions.DependencyInjection;
        ///using Newtonsoft.Json.Serialization;
        ///using XCommon.Application;
        ///using XCommon.Application.Login;
        ///using XCommon.Patterns.Ioc;
        ///using XCommon.Web.Authentication;
        ///using XCommon.Web.Authentication.Ticket;
        ///using XCommon.Web.Extensions;
        ///[{factoryUsing}]
        ///
        ///namespace [{namespace}]
        ///{
        ///    public class Startup
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AppStartStartup {
            get {
                return ResourceManager.GetString("AppStartStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using XCommon.Application.Login;
        ///using XCommon.Patterns.Ioc;
        ///
        ///namespace [{namespace}]
        ///{
        ///    public partial class Register
        ///    {
        ///        public static void RegisterCustom(bool unitTest)
        ///        {
        ///        }
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string FactoryRegister {
            get {
                return ResourceManager.GetString("FactoryRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /// &lt;binding ProjectOpened=&apos;dev:watch&apos; /&gt;
        ///var gulp = require(&apos;gulp&apos;),
        ///	gutil = require(&apos;gulp-util&apos;),
        ///	webpack = require(&apos;webpack&apos;),
        ///	htmlmin = require(&apos;gulp-htmlmin&apos;),
        ///	shell = require(&apos;gulp-shell&apos;),
        ///	livereload = require(&quot;gulp-livereload&quot;),
        ///	rimraf = require(&quot;gulp-rimraf&quot;),
        ///	webpackStream = require(&quot;webpack-stream&quot;),
        ///	merge = require(&apos;webpack-merge&apos;);
        ///
        ///var helper = {
        ///	tasks: {
        ///		clear: &quot;clear&quot;,
        ///		watch: &quot;dev:watch&quot;,
        ///		html: {
        ///			page: &quot;dev:html:page&quot;
        ///		},
        ///		dnx: {
        ///		    ts: &quot;dnx:typescri [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GulpFile {
            get {
                return ResourceManager.GetString("GulpFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /// &lt;binding ProjectOpened=&apos;dev:watch&apos; /&gt;
        ///var gulp = require(&apos;gulp&apos;),
        ///	gutil = require(&apos;gulp-util&apos;),
        ///	webpack = require(&apos;webpack&apos;),
        ///	htmlmin = require(&apos;gulp-htmlmin&apos;),
        ///	shell = require(&apos;gulp-shell&apos;),
        ///	livereload = require(&quot;gulp-livereload&quot;),
        ///	rimraf = require(&quot;gulp-rimraf&quot;),
        ///	webpackStream = require(&quot;webpack-stream&quot;),
        ///	merge = require(&apos;webpack-merge&apos;);
        ///
        ///var helper = {
        ///	tasks: {
        ///		clear: &quot;clear&quot;,
        ///		watch: &quot;dev:watch&quot;,
        ///		html: {
        ///			page: &quot;dev:html:page&quot;
        ///		},
        ///		default: {
        ///			dev: &quot;default:de [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GulpFileSimple {
            get {
                return ResourceManager.GetString("GulpFileSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;author&quot;: &quot;&quot;,
        ///  &quot;description&quot;: &quot;&quot;,
        ///  &quot;dependencies&quot;: {
        ///    &quot;@angular/common&quot;: &quot;2.0.0-rc.3&quot;,
        ///    &quot;@angular/compiler&quot;: &quot;2.0.0-rc.3&quot;,
        ///    &quot;@angular/core&quot;: &quot;2.0.0-rc.3&quot;,
        ///    &quot;@angular/http&quot;: &quot;2.0.0-rc.3&quot;,
        ///    &quot;@angular/platform-browser&quot;: &quot;2.0.0-rc.3&quot;,
        ///    &quot;@angular/platform-browser-dynamic&quot;: &quot;2.0.0-rc.3&quot;,
        ///    &quot;@angular/router&quot;: &quot;3.0.0-alpha.7&quot;,
        ///    &quot;core-js&quot;: &quot;^2.4.0&quot;,
        ///    &quot;reflect-metadata&quot;: &quot;^0.1.3&quot;,
        ///    &quot;rxjs&quot;: &quot;5.0.0-beta.6&quot;,
        ///    &quot;zone.js&quot;: &quot;0.6.12&quot;,
        ///    &quot;@angular2-material/button&quot;: &quot;^2.0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Package {
            get {
                return ResourceManager.GetString("Package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;version&quot;: &quot;1.0.0-*&quot;,
        ///  &quot;buildOptions&quot;: {
        ///    &quot;emitEntryPoint&quot;: true
        ///  },
        ///
        ///  &quot;dependencies&quot;: {
        ///    &quot;Microsoft.NETCore.App&quot;: {
        ///      &quot;type&quot;: &quot;platform&quot;,
        ///      &quot;version&quot;: &quot;1.0.0&quot;
        ///    },
        ///[{include}]
        ///    &quot;XCommon&quot;: &quot;1.0.28&quot;,
        ///    &quot;XCommon.CodeGerator&quot;: &quot;1.0.28&quot;
        ///  },
        ///
        ///  &quot;frameworks&quot;: {
        ///    &quot;netcoreapp1.0&quot;: {
        ///      &quot;imports&quot;: &quot;dnxcore50&quot;
        ///    }
        ///  }
        ///}
        ///.
        /// </summary>
        internal static string ProjectBusinessCodeGenerator {
            get {
                return ResourceManager.GetString("ProjectBusinessCodeGenerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;version&quot;: &quot;1.0.0-*&quot;,
        ///
        ///  &quot;dependencies&quot;: {
        ///    &quot;NETStandard.Library&quot;: &quot;1.6.0&quot;,
        ///[{include}]
        ///    &quot;XCommon&quot;: &quot;1.0.28&quot;,
        ///    &quot;XCommon.EF&quot;: &quot;1.0.28&quot;
        ///  },
        ///
        ///  &quot;frameworks&quot;: {
        ///    &quot;netstandard1.6&quot;: {
        ///					&quot;imports&quot;: [
        ///						&quot;dnxcore50&quot;,
        ///						&quot;portable-net452+win81&quot;
        ///					]
        ///    }
        ///  }
        ///}
        ///.
        /// </summary>
        internal static string ProjectBusinessConcrect {
            get {
                return ResourceManager.GetString("ProjectBusinessConcrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;version&quot;: &quot;1.0.0-*&quot;,
        ///
        ///  &quot;dependencies&quot;: {
        ///    &quot;NETStandard.Library&quot;: &quot;1.6.0&quot;,
        ///[{include}]
        ///    &quot;XCommon&quot;: &quot;1.0.28&quot;,
        ///    &quot;XCommon.EF&quot;: &quot;1.0.28&quot;
        ///  },
        ///
        ///  &quot;frameworks&quot;: {
        ///    &quot;netstandard1.6&quot;: {
        ///      &quot;imports&quot;: &quot;dnxcore50&quot;
        ///    }
        ///  }
        ///}
        ///.
        /// </summary>
        internal static string ProjectBusinessContract {
            get {
                return ResourceManager.GetString("ProjectBusinessContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;version&quot;: &quot;1.0.0-*&quot;,
        ///
        ///  &quot;dependencies&quot;: {
        ///    &quot;Microsoft.EntityFrameworkCore&quot;: &quot;1.0.0&quot;,
        ///    &quot;Microsoft.EntityFrameworkCore.Sqlite&quot;: &quot;1.0.0&quot;,
        ///    &quot;Microsoft.EntityFrameworkCore.SqlServer&quot;: &quot;1.0.0&quot;,
        ///    &quot;NETStandard.Library&quot;: &quot;1.6.0&quot;,
        ///[{include}]
        ///    &quot;XCommon&quot;: &quot;1.0.28&quot;
        ///  },
        ///
        ///  &quot;frameworks&quot;: {
        ///    &quot;netstandard1.6&quot;: {
        ///					&quot;imports&quot;: [
        ///						&quot;dnxcore50&quot;,
        ///						&quot;portable-net452+win81&quot;
        ///					]
        ///    }
        ///  }
        ///}
        ///.
        /// </summary>
        internal static string ProjectBusinessData {
            get {
                return ResourceManager.GetString("ProjectBusinessData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;version&quot;: &quot;1.0.0-*&quot;,
        ///
        ///  &quot;dependencies&quot;: {
        ///    &quot;NETStandard.Library&quot;: &quot;1.6.0&quot;,
        ///    &quot;XCommon&quot;: &quot;1.0.28&quot;
        ///  },
        ///
        ///  &quot;frameworks&quot;: {
        ///    &quot;netstandard1.6&quot;: {
        ///      &quot;imports&quot;: &quot;dnxcore50&quot;
        ///    }
        ///  }
        ///}
        ///.
        /// </summary>
        internal static string ProjectBusinessEntity {
            get {
                return ResourceManager.GetString("ProjectBusinessEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;version&quot;: &quot;1.0.0-*&quot;,
        ///
        ///  &quot;dependencies&quot;: {
        ///    &quot;NETStandard.Library&quot;: &quot;1.6.0&quot;,
        ///[{include}]
        ///    &quot;XCommon&quot;: &quot;1.0.28&quot;
        ///  },
        ///
        ///  &quot;frameworks&quot;: {
        ///    &quot;netstandard1.6&quot;: {
        ///					&quot;imports&quot;: [
        ///						&quot;dnxcore50&quot;,
        ///						&quot;portable-net452+win81&quot;
        ///					]
        ///    }
        ///  }
        ///}
        ///.
        /// </summary>
        internal static string ProjectBusinessFactory {
            get {
                return ResourceManager.GetString("ProjectBusinessFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;version&quot;: &quot;1.0.0-*&quot;,
        ///
        ///  &quot;dependencies&quot;: {
        ///    &quot;NETStandard.Library&quot;: &quot;1.6.0&quot;
        ///  },
        ///
        ///  &quot;frameworks&quot;: {
        ///    &quot;netstandard1.6&quot;: {
        ///      &quot;imports&quot;: &quot;dnxcore50&quot;
        ///    }
        ///  }
        ///}
        ///.
        /// </summary>
        internal static string ProjectBusinessResource {
            get {
                return ResourceManager.GetString("ProjectBusinessResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Project ToolsVersion=&quot;14.0&quot; DefaultTargets=&quot;Build&quot; xmlns=&quot;http://schemas.microsoft.com/developer/msbuild/2003&quot;&gt;
        ///  &lt;PropertyGroup&gt;
        ///    &lt;VisualStudioVersion Condition=&quot;&apos;$(VisualStudioVersion)&apos; == &apos;&apos;&quot;&gt;14.0&lt;/VisualStudioVersion&gt;
        ///    &lt;VSToolsPath Condition=&quot;&apos;$(VSToolsPath)&apos; == &apos;&apos;&quot;&gt;$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)&lt;/VSToolsPath&gt;
        ///  &lt;/PropertyGroup&gt;
        ///
        ///  &lt;Import Project=&quot;$(VSToolsPath)\DotNet\Microsoft.DotNet.Props&quot; Condition=&quot;&apos;$(V [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProjectClass {
            get {
                return ResourceManager.GetString("ProjectClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;dependencies&quot;: {
        ///    &quot;Microsoft.AspNetCore.Authentication.Cookies&quot;: &quot;1.0.0&quot;,
        ///    &quot;Microsoft.AspNetCore.Authentication.Google&quot;: &quot;1.0.0&quot;,
        ///    &quot;Microsoft.AspNetCore.Authentication.Facebook&quot;: &quot;1.0.0&quot;,
        ///    &quot;Microsoft.AspNetCore.Diagnostics&quot;: &quot;1.0.0&quot;,
        ///    &quot;Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore&quot;: &quot;1.0.0&quot;,
        ///    &quot;Microsoft.AspNetCore.Mvc&quot;: &quot;1.0.0&quot;,
        ///    &quot;Microsoft.AspNetCore.Server.IISIntegration&quot;: &quot;1.0.0&quot;,
        ///    &quot;Microsoft.AspNetCore.Server.Kestrel&quot;: &quot;1.0.0&quot;,
        ///    &quot;Microsoft.AspNetCore.Stat [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProjectViewWeb {
            get {
                return ResourceManager.GetString("ProjectViewWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Project ToolsVersion=&quot;14.0&quot; DefaultTargets=&quot;Build&quot; xmlns=&quot;http://schemas.microsoft.com/developer/msbuild/2003&quot;&gt;
        ///  &lt;PropertyGroup&gt;
        ///    &lt;VisualStudioVersion Condition=&quot;&apos;$(VisualStudioVersion)&apos; == &apos;&apos;&quot;&gt;14.0&lt;/VisualStudioVersion&gt;
        ///    &lt;VSToolsPath Condition=&quot;&apos;$(VSToolsPath)&apos; == &apos;&apos;&quot;&gt;$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)&lt;/VSToolsPath&gt;
        ///  &lt;/PropertyGroup&gt;
        ///  &lt;Import Project=&quot;$(VSToolsPath)\DotNet\Microsoft.DotNet.Props&quot; Condition=&quot;&apos;$(VST [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProjectWeb {
            get {
                return ResourceManager.GetString("ProjectWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Microsoft Visual Studio Solution File, Format Version 12.00
        ///# Visual Studio 14
        ///VisualStudioVersion = 14.0.25420.1
        ///MinimumVisualStudioVersion = 10.0.40219.1
        ///Project(&quot;{2150E333-8FDC-42A3-9474-1A3956D46DE8}&quot;) = &quot;Business&quot;, &quot;Business&quot;, &quot;{D7BCA6FC-0473-4EFC-A820-5E95DA0278E3}&quot;
        ///EndProject
        ///Project(&quot;{8BB2217D-0F2D-49D1-97BC-3654ED321F3B}&quot;) = &quot;Prospect.MyPetLife.Business.Contract&quot;, &quot;Prospect.MyPetLife.Business.Contract\Prospect.MyPetLife.Business.Contract.xproj&quot;, &quot;{439033F7-9CB4-43FB-87C3-435E6EC88333}&quot;
        ///End [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Solution {
            get {
                return ResourceManager.GetString("Solution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;compilerOptions&quot;: {
        ///		&quot;target&quot;: &quot;es5&quot;,
        ///		&quot;module&quot;: &quot;commonjs&quot;,
        ///		&quot;moduleResolution&quot;: &quot;node&quot;,
        ///		&quot;sourceMap&quot;: true,
        ///		&quot;emitDecoratorMetadata&quot;: true,
        ///		&quot;experimentalDecorators&quot;: true,
        ///		&quot;removeComments&quot;: false,
        ///		&quot;noImplicitAny&quot;: true,
        ///		&quot;suppressImplicitAnyIndexErrors&quot;: true
        ///	}
        ///}
        ///.
        /// </summary>
        internal static string TsConfig {
            get {
                return ResourceManager.GetString("TsConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;globalDependencies&quot;: {
        ///    &quot;core-js&quot;: &quot;registry:dt/core-js#0.0.0+20160317120654&quot;,
        ///    &quot;jasmine&quot;: &quot;registry:dt/jasmine#2.2.0+20160505161446&quot;,
        ///    &quot;node&quot;: &quot;registry:dt/node#4.0.0+20160509154515&quot;,
        ///    &quot;hammerjs&quot;: &quot;registry:dt/hammerjs#2.0.4+20160417130828&quot;
        ///  }
        ///}
        ///.
        /// </summary>
        internal static string Typings {
            get {
                return ResourceManager.GetString("Typings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;configuration&gt;
        ///
        ///  &lt;!--
        ///    Configure your application settings in appsettings.json. Learn more at http://go.microsoft.com/fwlink/?LinkId=786380
        ///  --&gt;
        ///
        ///  &lt;system.webServer&gt;
        ///    &lt;handlers&gt;
        ///      &lt;add name=&quot;aspNetCore&quot; path=&quot;*&quot; verb=&quot;*&quot; modules=&quot;AspNetCoreModule&quot; resourceType=&quot;Unspecified&quot;/&gt;
        ///    &lt;/handlers&gt;
        ///    &lt;aspNetCore processPath=&quot;%LAUNCHER_PATH%&quot; arguments=&quot;%LAUNCHER_ARGS%&quot; stdoutLogEnabled=&quot;false&quot; stdoutLogFile=&quot;.\logs\stdout&quot; forwardWindowsAuthToken=&quot;f [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Web {
            get {
                return ResourceManager.GetString("Web", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var path = require(&apos;path&apos;),
        ///	ExtractTextPlugin = require(&quot;extract-text-webpack-plugin&quot;),
        ///	webpack = require(&apos;webpack&apos;);
        ///
        ///module.exports = {
        ///	entry: [
        ///		&quot;./App/Polyfills.ts&quot;,
        ///		&quot;./App/Vendor.ts&quot;,
        ///		&quot;./App/App.Component.ts&quot;,
        ///        &quot;./App/Styles/App.Theme.scss&quot;
        ///	],
        ///	output: {
        ///		path: path.join(__dirname, &quot;wwwroot&quot;, &quot;asserts&quot;),
        ///		filename: &quot;bundle.js&quot;
        ///	},
        ///	plugins: [
        ///		new ExtractTextPlugin(&quot;bundle.css&quot;)
        ///	],
        ///
        ///	resolve: {
        ///		extensions: [&quot;&quot;, &quot;.js&quot;, &quot;.ts&quot;, &quot;.scss&quot;, &quot;.css&quot;]
        ///	},
        ///
        ///	module: {        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WebpackConfig {
            get {
                return ResourceManager.GetString("WebpackConfig", resourceCulture);
            }
        }
    }
}
